slurm_time: 2:00:00         # max runtime 1 hour
slurm_partition: gpu        # Partition used for the jobs
slurm_gres: gpu:1           # Use 1 GPU per job
slurm_job_name: benchopt    # Job name
slurm_additional_parameters:
  gpus-per-node: 1
  cpus-per-task: 10         # requires 10 CPUs per job
  # array: 1-10%2             # run 10 jobs in parallel
