slurm_time: 2:00:00         # max runtime 1 hour
slurm_gres: gpu:1           # requires 1 GPU per job
slurm_partition: gpu        # Partition used for the jobs
slurm_job_name: benchopt    # Job name
slurm_additional_parameters:
  ntasks: 1                 # Number of tasks per job
  cpus-per-task: 10         # requires 10 CPUs per job
